title: Welcome to secureblue!
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to secureblue!"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.

  can-we-harden-your-kargs:
    source: yafti.screen.consent
    values:
      title: Kernel hardening
      show_terminal: true
      description: |
        This step will enable additional kernel hardening. 
      actions:
        - run: pkexec ujust set-kargs-hardening

  can-we-harden-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Flatpak hardening
      show_terminal: true
      description: |
        This step will enable hardening for installed flatpaks.
      actions:
        - run: flatpak override --user --filesystem=host-os:ro --env=LD_PRELOAD=/var/run/host/usr/lib64/libhardened_malloc.so

  can-we-modify-your-flatpaks:
    source: yafti.screen.consent
    values:
      title: Flathub setup
      show_terminal: true
      description: |
        This step will therefore remove all basic Fedora Flatpaks from your system and replace it with Flathub's verified repository. It will also disable the system flatpaks in favor of user flatpaks.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-add --if-not-exists --user  flathub https://flathub.org/repo/flathub.flatpakrepo
  
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        Core Apps:
          description: Core system applications for the GNOME desktop environment.
          default: true
          packages:
            - Calculator: org.gnome.Calculator
            - Calendar: org.gnome.Calendar
            - Camera: org.gnome.Snapshot
            - Characters: org.gnome.Characters
            - Clocks: org.gnome.clocks
            - Connections: org.gnome.Connections
            - Contacts: org.gnome.Contacts
            - Disk Usage Analyzer: org.gnome.baobab
            - Document Scanner: org.gnome.SimpleScan
            - Document Viewer: org.gnome.Evince
            - Font Viewer: org.gnome.font-viewer
            - Image Viewer: org.gnome.Loupe
            - Logs: org.gnome.Logs
            - Maps: org.gnome.Maps
            - Sushi: org.gnome.NautilusPreviewer
            - Text Editor: org.gnome.TextEditor
            - Weather: org.gnome.Weather
            - Dialect: app.drey.Dialect
            - Athenticator: com.belmoussaoui.Authenticator
            - File Shredder: com.github.ADBeveridge.Raider
            - ungoogled-chromium: com.github.Eloston.UngoogledChromium
            - Cipher: com.github.arshubham.cipher
            - Wike: com.github.hugolabe.Wike
            - PDF Arranger: com.github.jeromerobert.pdfarranger
            - Foliate: com.github.johnfactotum.Foliate
            - Xournal++: com.github.xournalpp.xournalpp
            - RawTherapee: com.rawtherapee.RawTherapee
            - Sigil: com.sigil_ebook.Sigil
            - WPS Office: com.wps.Office
            - Pipeline: de.schmidhuberj.tubefeeder
            - Tuba: dev.geopjr.Tuba
            - Handbrake: fr.handbrake.ghb
            - Metadata Cleaner: fr.romainvigier.MetadataCleaner
            - Amberol: io.bassi.Amberol
            - Planify: io.github.alainm23.planify
            - Celluloid: io.github.celluloid_player.Celluloid
            - Paper Clip: io.github.diegoivan.pdf_metadata_editor
            - Switcheroo: io.gitlab.adhami3310.Converter
            - Footage: io.gitlab.adhami3310.Footage
            - NewsFlash: io.gitlab.news_flash.NewsFlash
            - Obsidian: md.obsidian.Obsidian
            - Lutris: net.lutris.Lutris
            - Scribus: net.scribus.Scribus
            - Audacity: org.audacityteam.Audacity
            - Blender: org.blender.Blender
            - Briar: org.briarproject.Briar
            - Cryptomator: org.cryptomator.Cryptomator
            - Gimp: org.gimp.GIMP
            - Builder: org.gnome.Builder
            - Fractal: org.gnome.Fractal
            - GnuCash: org.gnucash.GnuCash
            - Font Downloader: org.gustavoperedo.FontDownloader
            - Inkscape: org.inkscape.Inkscape
            - Krita: org.kde.krita
            - LibreOffice: org.libreoffice.LibreOffice
            - LocalSend: org.localsend.localsend_app
            - Mixxx: org.Mixxx.Mixxx
            - Parabolic: org.nickvision.tubeconverter
            - OnionShare: org.onionshare.OnionShare
            - Pitivi: org.pitivi.Pitivi
            - Signal: org.signal.Signal
            - VLC: org.videolan.VLC
            - Workbench: re.sonny.Workbench
            - Zoom: us.zoom.Zoom
            - Upscaler: io.gitlab.theevilskeleton.Upscaler
            
            
        System Apps:
          description: System applications
          default: true
          packages:
            - Flatseal: com.github.tchx84.Flatseal
            - Bottles: com.usebottles.bottles
            - GDM Settings: io.github.realmazharhussain.GdmSettings
            - PeaZip: io.github.peazip.PeaZip
            - KeePassXC: org.keepassxc.KeePassXC
            - Thunderbird: org.mozilla.Thunderbird
            - Firefox: org.mozilla.Firefox
            - Tor Browser Launcher: com.github.micahflee.torbrowser-launcher
            - Mullvad Browser: net.mullvad.MullvadBrowser
            - qpwgraph: org.rncbc.qpwgraph
            - Main Menu: page.codeberg.libre_menu_editor.LibreMenuEditor
            - Fedora Media Writer: org.fedoraproject.MediaWriter
            - Boxes: org.gnome.Boxes
            - Passwords and Keys: org.gnome.seahorse.Application
            - Extension Manager: com.mattjakeman.ExtensionManager
            

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Website":
            run: /usr/bin/xdg-open https://github.com/secureblue/secureblue
      description: |
        Thanks for trying secureblue, we hope you enjoy it!
