type: rpm-ostree
install:    
  - gnome-shell-extension-just-perfection
  - gnome-shell-extension-blur-my-shell
  - gnome-text-editor
  - firewall-config
  - gnome-disk-utility
  - libgda
  - libgda-sqlite
remove:
  - gnome-tour
  - yelp
  - gnome-user-share
  - mod_lua
  - httpd
  - httpd-core
  - mod_http2
  - mod_dnssd
  - gnome-remote-desktop
  - libvncserver
  - malcontent-ui-libs
  - malcontent-control
